#!/usr/bin/env bash
# A Bash script that displays a message and traps the SIGTERM signal

trap "echo 'I am invincible!!!'" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2 &
    wait $!
done
