#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
for i in {1..10}
do
    echo "Best School"
    # To silence SC2034, we acknowledge 'i' exists without needing it
    : "$i"
done
