#!/usr/bin/env bash
# This script provides information about a file named 'school'
if [ -e "school" ]
then
    echo "school file exists"
    
    # Check if empty
    if [ -s "school" ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    # Check if regular file
    if [ -f "school" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
